nome = str(input('Digite aqui o seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome e completo é {}.' .format(nome))
print('Seu nome escrito em maiúsculo é {}.' .format(nome.upper()))
print('Seu nome escrito em minúsculo é {}. ' .format(nome.lower()))
print('Seu nome completo tem um total de {} letras.' .format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome tem {} letras.' .format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e existem {} letras.' .format(separa[0], len(separa[0])))